/*CRIANDO O BANCO*/
CREATE DATABASE '/firebird/data/imersaosql.fdb'
  PAGE_SIZE 8192
  USER 'SYSDBA' PASSWORD 'masterkey';
COMMIT;

/******************************************************************************/
/***               Generated by IBExpert 28/06/2023 12:11:09                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_CLIENTES_ID;

CREATE TABLE CLIENTES (
    CLIENTES_ID    INTEGER NOT NULL,
    CLIENTE_NOME   VARCHAR(200) CHARACTER SET UTF8 NOT NULL,
    CLIENTE_ATIVO  SMALLINT DEFAULT -1 NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTES_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CLIENTES_BI */
CREATE OR ALTER TRIGGER CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.clientes_id is null) then
    new.clientes_id = gen_id(gen_clientes_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/******************************************************************************/
/***               Generated by IBExpert 28/06/2023 12:11:30                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_PRODUTOS_ID;

CREATE TABLE PRODUTOS (
    PRODUTOS_ID          INTEGER NOT NULL,
    PRODUTO_NOME         VARCHAR(250) CHARACTER SET UTF8 NOT NULL,
    PRODUTO_PRECO_VENDA  NUMERIC(11,2) NOT NULL,
    PRODUTO_PRECO_CUSTO  NUMERIC(11,2) NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (PRODUTOS_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: PRODUTOS_BI */
CREATE OR ALTER TRIGGER PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.produtos_id is null) then
    new.produtos_id = gen_id(gen_produtos_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/******************************************************************************/
/***               Generated by IBExpert 28/06/2023 12:11:39                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_VENDAS_ID;

CREATE TABLE VENDAS (
    VENDAS_ID    INTEGER NOT NULL,
    CLIENTES_ID  INTEGER NOT NULL,
    VENDA_DATA   DATE NOT NULL,
    VENDA_VALOR  NUMERIC(11,2) NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE VENDAS ADD CONSTRAINT PK_VENDAS PRIMARY KEY (VENDAS_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_1 FOREIGN KEY (CLIENTES_ID) REFERENCES CLIENTES (CLIENTES_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: VENDAS_BI */
CREATE OR ALTER TRIGGER VENDAS_BI FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.vendas_id is null) then
    new.vendas_id = gen_id(gen_vendas_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 28/06/2023 12:11:47                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_ITENS_VENDAS_ID;

CREATE TABLE ITENS_VENDAS (
    ITENS_VENDAS_ID   INTEGER NOT NULL,
    VENDAS_ID         INTEGER NOT NULL,
    PRODUTOS_ID       INTEGER NOT NULL,
    ITEM_VENDA_QTD    NUMERIC(11,2) NOT NULL,
    ITEM_VENDA_PRECO  NUMERIC(11,2) NOT NULL,
    ITEM_VENDA_CUSTO  NUMERIC(11,2) NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ITENS_VENDAS ADD CONSTRAINT PK_ITENS_VENDAS PRIMARY KEY (ITENS_VENDAS_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ITENS_VENDAS ADD CONSTRAINT FK_ITENS_VENDAS_1 FOREIGN KEY (VENDAS_ID) REFERENCES VENDAS (VENDAS_ID);
ALTER TABLE ITENS_VENDAS ADD CONSTRAINT FK_ITENS_VENDAS_2 FOREIGN KEY (PRODUTOS_ID) REFERENCES PRODUTOS (PRODUTOS_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ITENS_VENDAS_BI */
CREATE OR ALTER TRIGGER ITENS_VENDAS_BI FOR ITENS_VENDAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.itens_vendas_id is null) then
    new.itens_vendas_id = gen_id(gen_itens_vendas_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
